# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    post_install:
      - pip install Cython numpy
      - pip install d3rlpy>=1.1.1
      - pip install scipy>=1.10.1
      - pip install numpy>=1.22.4
      - pip install pandas>=1.5.3
      - pip install scikit-learn>=1.0.2
      - pip install matplotlib>=3.7.1
      - pip install seaborn>=0.11.2
      - pip install torch>=2.0.0
      - pip install d3rlpy>=1.1.1
      - pip install gym>=0.26.2
      - pip install gymnasium>=0.28.1
      - pip install hydra-core>=1.3.2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: docs/requirements.txt
